// app-react/src/components/lib/wrappers/SectionWrapper.js
import './wrappers.css';

// Props:
// headline = String, ex. "Hello world"
// headlineTagName = String, ex. "h1"


const SectionWrapper = ({ headline, headlineTagName, children }) => {

    const createHeadlineElement = () => {

        if (headlineTagName === "h1") {
            return <h1>{headline}</h1>
        }

        if (headlineTagName === "h2") {
            return <h2>{headline}</h2>
        }

        return <h1>Error. Please enter valid headLineTag ("h1" or "h2").</h1>
    }


    return (
        <div>
            <div className='section-wrapper-headline-container'>
                {createHeadlineElement()}
            </div>
            { children }
        </div>
    )
}

export default SectionWrapper

// app-svelte/src/lib/components/lib/status/wrappers/SectionWrapper.svelte
<script>
    export let headline
    export let headlineTagName

</script>

<div>
    <div class='section-wrapper-headline-container'>
        {#if headlineTagName === "h1"}
            <h1>{headline}</h1>
        {:else if headlineTagName === "h2"}
            <h2>{headline}</h2>
        {:else}
            <p>Error. Please enter valid headLineTag ("h1" or "h2").</p>
        {/if}
    </div>
    <slot></slot>
</div>


<style>

    .section-wrapper-headline-container {
        display: flex;
        align-items: center;
        height: 100px;
    }
</style>
