// app-react/src/components/lib/status/Status.js
import { useEffect } from "react"

// Props:
// messages = String[], if empty component will hide, ex. ["Form was succesfully sent."]
// type = "success" or "error", sets color.
// MSUntilClose = Number, if added setMessagesToClose runs after specified time has ellapsed, ex. 3000
// setMessagesToClose = function, runs after timeout if MSUntilClose is specified, ex. setMessages([])


const Status = ({ messages, type, MSUntilClose = null, setMessagesToClose = () => {} }) => {

    useEffect(() => {

        if (MSUntilClose && messages.length !== 0) {

            setTimeout(() => {

                setMessagesToClose()

            }, MSUntilClose)
        }

    }, [messages])
    

    if (messages.length === 0) {
        return null
    }


    return (
        <div 
            className={`${type === "error" ? 'error-color' : 'success-color'} info-container`}
            data-testid="status"
        >
            {
                messages.map((message, index) => (
                    <div key={index}>
                        <span>•</span>
                        <span>{message}</span> 
                    </div>
                ))
            }
        </div>
    )
}

export default Status

// app-svelte/src/lib/components/shared/status/Status.svelte
<script>
	import { createEventDispatcher } from "svelte";


    export let messages
    export let type
    export let MSUntilClose = null

    let dispatch = createEventDispatcher()
    $: {

        if (MSUntilClose && messages.length !== 0) {

            setTimeout(() => {

                dispatch("close")

            }, MSUntilClose)
        }
    }
</script>


{#if messages.length !== 0}
    <div 
        class="info-container {type === "error" ? 'error-color' : 'success-color'}"
        data-testid="status"
    >
        {#each messages as message}
            <div>
                <span>•</span>
                <span>{message}</span> 
            </div> 
        {/each}
    </div>
{/if}
