// app-svelte/src/lib/components/Forms/InputValidation.svelte
<script>
    export let hasError;
    export let format;

</script>


<div class="input-validation-container small-faded-text">
    <i class={`bi ${hasError ? 'bi-exclamation-circle-fill' : 'bi-check-circle-fill success-color'}`} />
    {format}
</div>


<style>
    .input-validation-container {
        margin: 6px 0 8px 0;
    }

    .input-validation-container i {
        margin-right: 8px;
    }

</style>

// app-react/src/components/Forms/InputValidation.js
// Props:
// format = String, ex. "YYYY-MM-DD-XXX"
// hasError = Boolean, decides icons, ex. example.length === 0

const InputValidation = ({ format, hasError}) => {

    return (
        <div className="input-validation-container small-faded-text">
            {   hasError ?
                    <i className="bi bi-exclamation-circle-fill" />
                    :
                    <i className="bi bi-check-circle-fill success-color" />
            }
            {format}
        </div>
    )
}

export default InputValidation
